### ISSUE TITLE
playlist option not working

### ISSUE THREAD

**Issue by wietseva** [svbnet/RedSea#1]
The playlist options isn't working for me, I get following error:

```
Traceback (most recent call last):
  File "redsea.py", line 129, in <module>
    main()
  File "redsea.py", line 120, in main
    md.download_media(track, config['tidal']['quality'], media_info)
  File "/mnt/files/Downloads/RedSea/mediadownloader.py", line 55, in download_media
    track_id = track_info['id']
KeyError: 'id'

```

**Comment by svbnet** [comment]
Fixed -- a8f570cb4eeda228f2f9db9c831e6d85de91f2aa
