### ISSUE TITLE
Updated some packages in arch, now get this when I run the program

### ISSUE THREAD

**Issue by shillshocked** [svbnet/RedSea#7]
Traceback (most recent call last):
  File "redsea.py", line 8, in <module>
    from tidal_api import TidalApi, TidalError
  File "/home/phoenix/RedSea-master-lossless/tidal_api.py", line 4, in <module>
    import requests
  File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'

**Comment by shillshocked** [comment]
Workaround: manually delete /usr/lib/python3.5/site-packages/requests/packages/{urllib3,chardet}, as they are not owned by python-requests.
